name: Upload and Download Artifact

on:
  push:
    branches:
      - main

jobs:
  upload-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create a file
        run: |
          echo "This is a test file" > test-file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-file
          path: test-file.txt

  download-file:
    runs-on: ubuntu-latest
    needs: upload-file
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: test-file

      - name: Use the file
        run: cat test-file.txt
