name: Browse Local File in Workflow
on:
  workflow_dispatch:
    inputs:
      my-file-input:
        description: 'A file input example'
        required: true
        default: 'path/to/my-file.txt'
      environment:
        type: environment
        description: Select the environment
      boolean:
        type: boolean
        description: True or False
     
jobs:
  build:
    runs-on: ubuntu-latest
