name: CI input json

on:
  workflow_dispatch:
    inputs:
      user-input:
        description: 'A file input example'
        required: true
        default: 'path/to/my-file.txt'      
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.user-input }} / ${{ inputs.user-input }}"
         
          
