name: Browse Local File in Workflow
on:
  workflow_dispatch:

jobs:
  browse-file:
    runs-on: ubuntu-latest

    steps:
      - name: Upload file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: local-file
          path: path/to/local-file.txt

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: local-file
          path: downloaded-file

      - name: Use the file
        run: cat downloaded-file/local-file.txt
